Separate functions that manage database

diff --git a/LectureManager b/LectureManager
--- a/LectureManager
+++ b/LectureManager
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 # Maintains a list of Courses that are currently active on the system. Allowing
 # for the user to easily access information and file path to the specified
@@ -27,11 +27,21 @@
 
 # Display the Usage Documentation message
 usage() {
-	echo "Usage: $0 [-aglh] [-c course]"
-	echo "	-a	Add a Course"
-	echo "	-l	List Courses"
-	echo "	-g	Get Course Directory"
+	echo -n "Usage: $0 [-aglh] [-c course]
+
+Help maintain and manage Notes for specified courses on the Users system.
+
+ Options:
+  -h	Display usage message
+  -a	Add a Course
+  -l	List Courses
+  -g	Get Course Directory
+"
 }
+
+################################################################################
+# Course management Database functions
+# 	Functions dedicated to parsing and interacting with the Course Database
 
 # Set the Database file for the Program, or create one if it doesnt exist.
 #	The Database shall contain all information regarding courses
@@ -51,8 +61,80 @@ init_db() {
 	# Setup basic JSON for empty file
 	if [[ $DB_FILE == "" ]]; then
 		echo "Config empty, Generating new"
-		echo "{\"Courses\":{}}" > $DB_PATH
+		echo "{\"Courses\":{}}" | jq > $DB_PATH
 	fi
+}
+
+# Determines if a Course with the specified name currently exists in the
+# database
+# Arguments:
+#		Course name
+# Returns:
+#		0 if the Course exists, otherwise non-zero
+course_exists () {
+	local COURSE_NAME="$1"
+	local QUERY=$(printf "jq -e '.[] | select( .| has(\"%s\"))'" $COURSE_NAME)
+
+	( eval $QUERY <<< $DB_FILE > /dev/null )
+	return $?
+}
+
+# Add Course to Data Structure
+# Arguments:
+#	Course Name
+#	Directry
+add_course_to_db() {
+	local COURSE_NAME="$1"
+	local DIRECTORY_PATH="$2"
+
+	# Database query to Add Course
+	QUERY=$(printf "jq '.Courses += {\"%s\": {\"dir\": \"%s\"}}' test.json" \
+		"$COURSE_NAME" \
+		"$DIRECTORY_PATH")
+
+ 	DB=$(eval $QUERY)
+
+	cp "$DB_PATH" "${DB_PATH}.bak"
+ 	echo $DB > "$DB_PATH"
+}
+
+# Return the Directory that corresponds to the specified Course, if it exists
+#
+# GLOBAL:
+#	DIRECTORY - Path to the specified course
+# Arguments:
+#	Course - Name of Course to search
+# Returns:
+#	0 on success, otherwise non-zero
+get_course_directory () {
+	local COURSE
+	COURSE="$1"
+
+	# Determine if a course was specified
+	if [[ -z $COURSE ]] || [[ "$COURSE" == "" ]]; then
+		echo "No Course specified"
+		exit 1
+	fi
+
+	DIRECTORY=$(jq -r --arg v "$COURSE" '.Courses[$v].dir' <<< $DB_FILE)
+
+	if [[ $DIRECTORY == "null" ]]; then
+		return 1
+	fi
+
+}
+
+# Display the Courses that currently exist in the Database
+get_courses () {
+	readarray -t CourseNames < <(echo $DB_FILE | jq -r ".Courses | keys[]")
+
+	if (( ${#CourseNames[@]} == 0 )); then
+		echo "No Courses currently exist in the database."
+		echo "You may add one by using -a option"
+		exit
+	fi
+
+	printf "%s\n" "${CourseNames[@]}"
 }
 
 ################################################################################
@@ -67,9 +149,9 @@ handle_add_course() {
 		read COURSE_NAME
 	done
 
-	exists_course "$COURSE_NAME"
+	course_exists "$COURSE_NAME"
 
-	if [[ $? ]]; then
+	if [[ $? == 0 ]]; then
 		echo "A Course by that name already exists."
 		exit 1
 	fi
@@ -97,118 +179,23 @@ handle_add_course() {
 	add_course_to_db "$COURSE_NAME" "$DIRECTORY_PATH"
 }
 
-# Add Course to Data Structure
-# Args:
-#	1 Course Name
-#	Directry
-add_course_to_db() {
-	local COURSE_NAME="$1"
-	local DIRECTORY_PATH="$2"
+# Outputs a list of Lectures that belongs to the specified Course if it exists
+# Arguments:
+#	Course name
+get_course_lectures () {
+	local COURSE
+	COURSE="$1"
 
-	# Query to Add Course
-	QUERY=$(printf "jq '.Courses += {\"%s\": {\"dir\": \"%s\"}}' test.json" \
-		"$COURSE_NAME" \
-		"$DIRECTORY_PATH")
- 	DB=$(eval $QUERY)
+	get_course_directory "$COURSE"
 
-	# DAtabase Connection
-	cp "$DB_PATH" "${DB_PATH}.bak"
- 	echo $DB > "$DB_PATH"
-}
-
-# Display the Courses that currently exist in the Database
-get_courses () {
-	readarray -t CourseNames < <(echo $DB_FILE | jq -r ".Courses | keys[]")
-
-	if (( ${#CourseNames[@]} == 0 )); then
-		echo "No Courses currently exist in the database."
-		echo "You may add one by using -a option"
+	if [[ $? == 1 ]]; then
+		echo "Course doesn't exist in Database."
 		exit
 	fi
 
-	printf "%s\n" "${CourseNames[@]}"
-}
-
-# Display the list of Courses that exist and their path
-show_course_directory () {
-	readarray -t arr < <(echo $DB_FILE | jq -r ".Courses | keys[]" )
-
-	for course in "${arr[@]}"; do
-		echo $course
-		DIR=$( jq -r ".Courses.$course" <<< $DB_FILE )
-		echo "Directory $DIR"
-	done
-
-	unset arr
-}
-
-# Return the Directory that corresponds to the specified Course, if it exists
-# Exits on failure, returning 1
-# Argument:
-#	Course - Name of Course to search
-# Returns:
-#	DIRECTORY - Path to the specified course
-get_course_directory () {
-	COURSE="$1"
-	if [[ -z $COURSE ]] || [[ "$COURSE" == "" ]]; then
-		echo "No Course specified"
-		exit 1
-	fi
-
-	DIRECTORY=$(jq -r --arg v "$COURSE" '.Courses[$v].dir' <<< $DB_FILE)
-
-	if [[ $DIRECTORY == "null" ]]; then
-		exit 1
-	else
-		echo $DIRECTORY
-	fi
-
-	unset $COURSE
-}
-
-# Outputs a list of Lectures that belongs to the specified Course if it exists
-# Arguments: Course Name
-#
-get_course_lectures () {
-	COURSE="$1"
-	getCourseDirectory "$COURSE"
-
+	# List Lectures contained in the Course
 	ls "$DIRECTORY" | grep "Lecture" | sort --version-sort
 }
-
-# Determines if a Course with the specified name currently exists in the
-# database
-#	Arguments: Course name
-#	Returns: 0 if course exists, otherwise 1
-exists_course () {
-	local COURSE_NAME="$1"
-
-	local QUERY=$(printf "jq -e '.[] | select( .| has(\"%s\"))'" $COURSE_NAME)
-
-	local EXISTS
-	EXISTS=$(eval $QUERY <<< $DB_FILE)
-
-	if [[ $? == 0 ]]; then
-		return 0
-	fi
-
-	return 1
-}
-
-# Get all subkeys
-# TEST=$(cat test.json | jq -r ".Courses | keys[]")
-
-# Read a JSON Array file into an Bash Array
-# readarray -t lectureDirectories < <(cat test.json | jq -r ".lecdir[]" )
-#
-# for t in  "${lectureDirectories[@]}"; do
-# 	echo $t
-# done
-
-#echo $TEST
-#readarray -t arr <<< $TEST
-#
-#printf "%s\n" "${arr[@]}"
 
 ################################################################################
 
@@ -228,7 +215,7 @@ while getopts ":lahg:c:e:" o; do
 			;;
 		e)
 			courseName=${OPTARG}
-			exists_course $courseName
+			course_exists $courseName
 			echo $?
 			;;
 		g)
