Refactor handler functions

diff --git a/notemgr b/notemgr
--- a/notemgr
+++ b/notemgr
@@ -27,11 +27,9 @@
 
 # Display the Usage Documentation message
 usage() {
-	echo -n "Usage:
-
-$0 [OPTIONS]
-$0 Course			Display all Lectures in course
-$0 Course Lecture	Print path to the specific lecture
+	echo -n "Usage: $0 [OPTIONS]
+$0 [Course]		Display all Lectures in course
+$0 [Course] [Lecture]	Print path to the specific lecture
 
 Help maintain and manage Notes for the specified courses on the Users system.
 
@@ -50,11 +48,8 @@ Help maintain and manage Notes for the specified courses on the Users system.
 handle_display_lectures () {
 	local COURSE_NAME="$1"
 
-	course_exists "$COURSE_NAME"
-
-	if [[ $? != 0 ]]; then
-		printf "The course, %s, doesn't exist in the database." \
-			"$COURSE_NAME"
+	if ! course_exists "$COURSE_NAME"; then
+		echo "The course $COURSE_NAME doesn't exist in the database."
 		exit 1
 	fi
 
@@ -70,7 +65,6 @@ handle_display_lectures () {
 
 	# List Lectures contained in the Course
 	ls "$DIRECTORY" | grep "Lecture" | sort --version-sort
-
 }
 
 # Determine the file name of the new Lecture in the specified course
@@ -78,6 +72,12 @@ handle_display_lectures () {
 #	Course Name
 handle_create_lecture () {
 	local COURSE_NAME="$1"
+
+	if ! course_exists "$COURSE_NAME"; then
+		echo "The course $COURSE_NAME doesn't exist in the database."
+		echo "Cannot create Lecture for a non-existant course"
+		exit 1
+	fi
 
 	if is_course_archived "$COURSE_NAME"; then
 		echo -n "The course $COURSE_NAME has been archived."
@@ -87,10 +87,6 @@ handle_create_lecture () {
 
 	# Obtain the number of Lectures that currently exist
 	local LECTURE_NUM=$(handle_display_lectures "$COURSE_NAME" | wc -l )
-
-	if [[ $LECTURE_NUM -eq 0 ]]; then
-		echo "Lecture1.md"
-	fi
 
 	# Next Lecture name will be LECTURE_NUM+1
 	printf "Lecture%d.md\n" $((LECTURE_NUM+1))
@@ -158,16 +154,18 @@ done
 
 shift $((OPTIND-1))
 
-## Handle non-specific
+## Handle non-specific argument options
+# 0 Args 	display courses
+# 1 Args	Display Lectures for Course
+# 2 Args	Display path to specified Lecture
 
-if [[ $OPTIND -eq 1 ]] && [[ $# == 0 ]]; then
+if [[ $# == 0 ]]; then
 	get_courses
-	exit
 # Otherwise Handle Course only when 1 argument
 elif [[ $# == 1 ]]; then
 	handle_display_lectures "$1"
-	exit
 elif [[	$# == 2 ]]; then
 	handle_display_lecture_path "$@"
-	exit
+else
+	usage
 fi
diff --git a/notemgr-lib b/notemgr-lib
--- a/notemgr-lib
+++ b/notemgr-lib
@@ -2,10 +2,9 @@
 #
 # Library functions to be used for notemgr and its sub-commands
 
-
 ################################################################################
-# Course management Database functions
-# 	Functions dedicated to parsing and interacting with the Course Database
+# Database functions
+# 	Functions dedicated to directly interacting with the Course Database
 
 # Set the Database file for the Program, or create one if it doesnt exist.
 #	The Database shall contain all information regarding courses
@@ -42,31 +41,6 @@ course_exists () {
 
 	( eval $QUERY <<< $DB_FILE > /dev/null )
 	return $?
-}
-
-# Checks if the first argument, a list, contains the second argument inside of
-# it.
-# $1 List to check
-# $2 Item to find
-contains () {
-	if [[ $1 =~ (^|[[:space:]])"$2"($|[[:space:]]) ]]; then
-		return 0
-	fi
-	return 1
-}
-
-# Determine if the Lecture belongs to the Course
-# Arguments
-# $1 Course to check
-# $2 Lecture
-# Returns:
-# 0 if Lecture is found, otherwise non-zero
-lecture_exists () {
-	local COURSE="$1"
-	local LECTURE_NAME="$2"
-	local LECTURE_NUM=(handle_display_lectures "$COURSE_NAME")
-
-	`contains "$1" "$2"` && return 1 || return 0
 }
 
 # Add Course to Data Structure
@@ -161,4 +135,33 @@ is_course_archived () {
 
 	[[ "$QUERY" == "true" ]] && return 0 || return 1
 }
+
+################################################################################
+# Helper functions
+
+# Checks if the first argument, a list, contains the second argument inside of
+# it.
+# $1 List to check
+# $2 Item to find
+contains () {
+	if [[ $1 =~ (^|[[:space:]])"$2"($|[[:space:]]) ]]; then
+		return 0
+	fi
+	return 1
+}
+
+# Determine if the Lecture belongs to the Course
+# Arguments
+# $1 Course to check
+# $2 Lecture
+# Returns:
+# 0 if Lecture is found, otherwise non-zero
+lecture_exists () {
+	local COURSE="$1"
+	local LECTURE_NAME="$2"
+	local LECTURE_NUM=(handle_display_lectures "$COURSE_NAME")
+
+	`contains "$1" "$2"` && return 1 || return 0
+}
+
 
